### PR TITLE
fix(go): bullet-proof against nil dereferences + more fuzzers

### LINKED ISSUE #241: LeafOp.CheckAgainstSpec panics on nil spec argument
There isn’t validation that the input spec value is non-nil which causes a nil dereference.

## Exhibit

```go
func TestReproLeafOpNilSpec(t *testing.T) {
        proof := &ics23.ExistenceProof{
                Leaf: &ics23.LeafOp{PrehashValue: 1, Length: 1, Prefix: nil},
        }
        _ = proof.CheckAgainstSpec(nil)
}
```
which produces

```shell
$ go test -run=TestReproLeafOpNilSpec
--- FAIL: TestReproLeafOpNilSpec (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd1e0fb2]

goroutine 6 [running]:
testing.tRunner.func1.2({0xd2ad460, 0xd5358a0})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1634 +0x377
panic({0xd2ad460?, 0xd5358a0?})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:763 +0x132
github.com/cosmos/ics23/go.(*LeafOp).CheckAgainstSpec(0x541976a0?, 0xd600108?)
	/Users/emmanuelodeke/go/src/github.com/cosmos/ics23/go/ops.go:93 +0x12
github.com/cosmos/ics23/go.(*ExistenceProof).CheckAgainstSpec(0xc000145f10, 0x0)
	/Users/emmanuelodeke/go/src/github.com/cosmos/ics23/go/proof.go:187 +0x3b
github.com/cosmos/ics23/go_test.TestReproLeafOpNilSpec(0xc00022e1a0?)
	/Users/emmanuelodeke/go/src/github.com/cosmos/ics23/go/repro_test.go:26 +0x6b
testing.tRunner(0xc00022e1a0, 0xd307518)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1682 +0xfb
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1735 +0x390
exit status 2
```

## Fix
Immediately check that the value of spec is non-nil before dereferencing

/cc @elias-orijtech @julienrbrt

### LINKED ISSUE #242: LeafOp.CheckAgainstSpec panics on nil spec.LeafSpec value
Please see
```go
func TestReproLeafOpNilSpecDotLeafSpec(t *testing.T) {
        proof := &ics23.ExistenceProof{
                Leaf: &ics23.LeafOp{PrehashValue: 1, Length: 1, Prefix: nil},
        }               
        spec := &ics23.ProofSpec{
                LeafSpec: nil,
        }
        _ = proof.CheckAgainstSpec(spec)
}
```

which produces

```shell
$ go test -run=TestReproLeafOpNilSpecDotLeafSpec
--- FAIL: TestReproLeafOpNilSpecDotLeafSpec (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcd71015]

goroutine 6 [running]:
testing.tRunner.func1.2({0xce3d460, 0xd0c58a0})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1634 +0x377
panic({0xce3d460?, 0xd0c58a0?})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:763 +0x132
github.com/cosmos/ics23/go.(*LeafOp).CheckAgainstSpec(0xc000218750, 0xd190108?)
	/Users/emmanuelodeke/go/src/github.com/cosmos/ics23/go/ops.go:108 +0x75
github.com/cosmos/ics23/go.(*ExistenceProof).CheckAgainstSpec(0xc000145f10, 0xc000145ef0)
	/Users/emmanuelodeke/go/src/github.com/cosmos/ics23/go/proof.go:187 +0x3b
github.com/cosmos/ics23/go_test.TestReproLeafOpNilSpecDotLeafSpec(0xc00022e1a0?)
	/Users/emmanuelodeke/go/src/github.com/cosmos/ics23/go/repro_test.go:36 +0x7a
testing.tRunner(0xc00022e1a0, 0xce97520)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1682 +0xfb
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1735 +0x390
exit status 2
```

## Fix
```diff
@@ -91,6 +91,9 @@ func (op *InnerOp) Apply(child []byte) ([]byte, error) {
 // CheckAgainstSpec will verify the LeafOp is in the format defined in spec
 func (op *LeafOp) CheckAgainstSpec(spec *ProofSpec) error {
        lspec := spec.LeafSpec
+       if lspec == nil {
+               return errors.New("spec.LeafSpec must be non-nil")
+       }
 
        if validateSpec(spec) {
                err := validateIavlOps(op, 0)
```

### LINKED ISSUE #243: ProofSpec.SpecEquals panics with nil dereferences: needs better bullet proofing
The code in https://github.com/cosmos/ics23/blob/d583e12161752926a12c85bb0dfc9887fb26f315/go/proof.go#L454-L464 doesn’t perform any prior checks to ensure that there are no nil dereferences

which can be reached by a bunch of simple nil values

## Reproduction
```go
func TestReproPanickingLeafSpecSpecEquals(t *testing.T) {
	// 1. Nil proof, nil Spec
	proof := (*ics23.ExistenceProof)(nil)
	_ = proof.CheckAgainstSpec(nil)

	// 2. Nil proof, non-nil Spec
	spec := &ics23.ProofSpec{
		LeafSpec: nil,
	}
	_ = proof.CheckAgainstSpec(spec)

	// 3. Non-nil proof, nil spec
	proof = &ics23.ExistenceProof{
		Leaf: &ics23.LeafOp{PrehashValue: 1, Length: 1, Prefix: nil},
	}
	_ = proof.CheckAgainstSpec(nil)

	// 4. (Non-nil proof, (non-nil spec, nil spec.LeafSpea))
	_ = proof.CheckAgainstSpec(spec)

	// 5. ((Non-nil proof, nil LeafSpec), non-nil spec)
	proof.LeafSpec = nil
	_ = proof.CheckAgainstSpec(spec)

	// 6. ((Non-nil proof, nil InnerSpec), (non-nil spec, non-nil InnerSpec))
	proof = &ics23.ExistenceProof{
		Leaf: &ics23.LeafOp{PrehashValue: 1, Length: 1, Prefix: prefix},
		Path: []*ics23.InnerOp{{Hash: 1}},
	}
	spec = &ics23.ProofSpec{
		LeafSpec:  &ics23.LeafOp{PrehashValue: 1, Length: 1, Prefix: prefix},
		InnerSpec: &ics23.InnerSpec{Hash: 1},
	}
	_ = proof.CheckAgainstSpec(spec)
}
```

but it could pre-vet the values can be dereferenced by this improvement

```diff
// over-declares equality, which we cosnider fine for now.
 func (p *ProofSpec) SpecEquals(spec *ProofSpec) bool {
-       return p.LeafSpec.Hash == spec.LeafSpec.Hash &&
-               p.LeafSpec.PrehashKey == spec.LeafSpec.PrehashKey &&
-               p.LeafSpec.PrehashValue == spec.LeafSpec.PrehashValue &&
-               p.LeafSpec.Length == spec.LeafSpec.Length &&
-               p.InnerSpec.Hash == spec.InnerSpec.Hash &&
-               p.InnerSpec.MinPrefixLength == spec.InnerSpec.MinPrefixLength &&
-               p.InnerSpec.MaxPrefixLength == spec.InnerSpec.MaxPrefixLength &&
-               p.InnerSpec.ChildSize == spec.InnerSpec.ChildSize &&
-               len(p.InnerSpec.ChildOrder) == len(spec.InnerSpec.ChildOrder)
+       // 1. Compare LeafSpecs values.
+       switch {
+       case (p.LeafSpec == nil) != (spec.LeafSpec == nil): // One of them is nil.
+               return false
+
+       case p.LeafSpec != nil && spec.LeafSpec != nil:
+               ok := p.LeafSpec.Hash == spec.LeafSpec.Hash &&
+                       p.LeafSpec.PrehashKey == spec.LeafSpec.PrehashKey &&
+                       p.LeafSpec.PrehashValue == spec.LeafSpec.PrehashValue &&
+                       p.LeafSpec.Length == spec.LeafSpec.Length
+               if !ok {
+                       return false
+               }
+
+       default: // Both are nil, hence LeafSpec values are equal.
+       }
+
+       // 2. Compare InnerSpec values.
+       switch {
+       case (p.InnerSpec == nil) != (spec.InnerSpec == nil): // One of them is not nil.
+               return false
+
+       case p.InnerSpec != nil && spec.InnerSpec == nil: // Both are non-nil
+               ok := p.InnerSpec.Hash == spec.InnerSpec.Hash &&
+                       p.InnerSpec.MinPrefixLength == spec.InnerSpec.MinPrefixLength &&
+                       p.InnerSpec.MaxPrefixLength == spec.InnerSpec.MaxPrefixLength &&
+                       p.InnerSpec.ChildSize == spec.InnerSpec.ChildSize &&
+                       len(p.InnerSpec.ChildOrder) == len(spec.InnerSpec.ChildOrder)
+               if !ok {
+                       return false
+               }
+
+       default: // Both are nil, hence InnerSpec values are equal.
+       }
+
+       // By this point all the above conditions pass so they are equal.
+       return true
 }
```

/cc @elias-orijtech @julienrbrt

### PR DESCRIPTION
**Pull request by odeke-em**
This change fixes a bunch of issues identified by Orijtech Inc's audit
of ics23 which is a critical cosmos-sdk dependency and as per reports
about the Dragonberry & Elderberry vulnerability reports, this package
was put back on our radar to further audit and voila that uncovered
some issues, some of which have beenfixed in this change. While here
also added more fuzzers. To ensure that the fuzzers can run alright,
added -short to any invocations of "go test".

Fixes #241
Fixes #242
Fixes #243

### CODE REVIEW

**Comment by odeke-em** [comment]
Kindly cc-ing @crodriguezvega

**Comment by crodriguezvega** [comment]
> Kindly cc-ing @crodriguezvega

Thank you for opening the issues and this PR, @odeke-em. I will review this week.

File: go/proof.go [hunk 1]
```diff
@@ -452,13 +452,41 @@ func orderFromPadding(spec *InnerSpec, inner *InnerOp) (int32, error) {
...
-		p.LeafSpec.PrehashValue == spec.LeafSpec.PrehashValue &&
-		p.LeafSpec.Length == spec.LeafSpec.Length &&
-		p.InnerSpec.Hash == spec.InnerSpec.Hash &&
-		p.InnerSpec.MinPrefixLength == spec.InnerSpec.MinPrefixLength &&
-		p.InnerSpec.MaxPrefixLength == spec.InnerSpec.MaxPrefixLength &&
-		p.InnerSpec.ChildSize == spec.InnerSpec.ChildSize &&
-		len(p.InnerSpec.ChildOrder) == len(spec.InnerSpec.ChildOrder)
+	// 1. Compare LeafSpecs values.
+	switch {
+	case (p.LeafSpec == nil) != (spec.LeafSpec == nil): // One of them is nil.
```
Comment (crodriguezvega) [inline go/proof.go:457]: Same here:

```suggestion
	case (p.LeafSpec == nil) || (spec.LeafSpec == nil): // One of them is nil.
```

File: go/proof_data_test.go [hunk 2]
```diff
@@ -13,18 +13,18 @@ type ExistenceProofTestStruct struct {
 	Expected []byte
 }
 
-func ExistenceProofTestData(t *testing.T) map[string]ExistenceProofTestStruct {
-	t.Helper()
+func ExistenceProofTestData(tb testing.TB) map[string]ExistenceProofTestStruct {
```
Comment (crodriguezvega) [inline go/proof_data_test.go:16]: Is it really necessary to change the interface if we're not doing benchmarking?

File: go/ops.go [hunk 3]
```diff
@@ -94,7 +94,13 @@ func (op *InnerOp) Apply(child []byte) ([]byte, error) {
 
 // CheckAgainstSpec will verify the LeafOp is in the format defined in spec
 func (op *LeafOp) CheckAgainstSpec(spec *ProofSpec) error {
+	if op == nil || spec == nil {
```
Comment (crodriguezvega) [inline go/ops.go:97]: Do we really need to check if the pointer receiver is `nil`? If it's `nil` wouldn't an attempt to call this function already cause a nil pointer dereference panic?

File: go/ops.go [hunk 4]
```diff
@@ -123,6 +129,16 @@ func (op *LeafOp) CheckAgainstSpec(spec *ProofSpec) error {
 
 // CheckAgainstSpec will verify the InnerOp is in the format defined in spec
 func (op *InnerOp) CheckAgainstSpec(spec *ProofSpec, b int) error {
+	if spec == nil || op == nil {
```
Comment (crodriguezvega) [inline go/ops.go:132]: Same comment here about check `op == nil`.

File: go/ops.go [hunk 5]
```diff
@@ -123,6 +129,16 @@ func (op *LeafOp) CheckAgainstSpec(spec *ProofSpec) error {
...
+		return errors.New("op and spec must be both non-nil")
+	}
+	if spec.InnerSpec == nil {
+		return errors.New("spec.InnerSpec must be non-nil")
+	}
+	if spec.LeafSpec == nil {
+		return errors.New("spec.LeafSpec must be non-nil")
+	}
```
Comment (crodriguezvega) [inline go/ops.go:140]: I might be missing something, but when I commented out this code, no test fails. Is the fuzzer correctly generating a test case for this scenario? The fuzzing test fails if I remove the checks for `InnerSpec` and `InnerSpec.ChildSize`.

File: go/fuzz_test.go [hunk 6]
```diff
@@ -122,3 +155,49 @@ func FuzzCombineProofs(f *testing.F) {
...
 	})
 }
+
+type verifyJSON struct {
+	Proof *CommitmentProof
+	Ref   *RefData
+	Spec  *ProofSpec
+}
+
+func FuzzVerifyMembership(f *testing.F) {
```
Comment (crodriguezvega) [inline go/fuzz_test.go:165]: Just a code organisation nit: I would move the type and the test a bit up just after `FuzzVerifyNonMembership`.

File: go/fuzz_test.go [hunk 7]
```diff
@@ -122,3 +155,49 @@ func FuzzCombineProofs(f *testing.F) {
...
+		if err := json.Unmarshal(input, &con); err != nil {
+			return
+		}
+		spec, ref, proof := con.Spec, con.Ref, con.Proof
+		if ref == nil {
+			return
+		}
+		_ = VerifyMembership(spec, ref.RootHash, proof, ref.Key, ref.Value)
+	})
+}
```
Comment (crodriguezvega) [inline go/fuzz_test.go:203]: Wondering if we could also write this test like this:

```go
func FuzzVerifyMembership(f *testing.F) {
	if testing.Short() {
		f.Skip("in -short mode")
	}

	// 1. Add some seeds.
	for _, batchVec := range batchVectorDataSeeds {
		blob, err := json.Marshal(batchVec)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(blob)
	}

	// 2. Now let's run the fuzzer.
	f.Fuzz(func(t *testing.T, input []byte) {
		var bv BatchVectorData
		if err := json.Unmarshal(input, &bv); err != nil {
			return
		}

		if bv.Ref == nil || bv.Proof == nil || bv.Ref.RootHash == nil {
			return
		}

		root, err := bv.Proof.Calculate()
		if err != nil {
			return
		}

		if !bytes.Equal(bv.Ref.RootHash, root) {
			return
		}

		_ = VerifyMembership(bv.Spec, bv.Ref.RootHash, bv.Proof, bv.Ref.Key, bv.Ref.Value)
	})
}
```

Because then it follows a similar structure as `FuzzVerifyNonMembership` and we don't need the extra `verifyJSON` type.

File: go/Makefile [hunk 8]
```diff
@@ -1,5 +1,5 @@
 test:
-	go test .
+	go test -short .
```
Comment (crodriguezvega) [inline go/Makefile:2]: Why add the flag? Even if we don't skip the tests, it doesn't take that long to run them.

**Review by crodriguezvega — COMMENTED** [review]
Thanks a lot for bulletproofing the code, @odeke-em! I have left a bunch of comments for now; let me know what you think about them.

File: go/proof.go [hunk 9]
```diff
@@ -452,13 +452,41 @@ func orderFromPadding(spec *InnerSpec, inner *InnerOp) (int32, error) {
...
+		if !ok {
+			return false
+		}
+
+	default: // Both are nil, hence LeafSpec values are equal.
+	}
+
+	// 2. Compare InnerSpec values.
+	switch {
+	case (p.InnerSpec == nil) != (spec.InnerSpec == nil): // One of them is not nil.
```
[the remark this answers is not in the document]
Comment (odeke-em) [reply go/proof.go:474]: But that changes the entire meaning of it and doesn't make the conditions pass: for the condition that both are nil we want that to pass, please take a look again at the 3 cases in the switch.

File: go/proof.go (hunk 1 above)
Comment (odeke-em) [reply go/proof.go:457]: Ditto about that changing the conditions

File: go/proof_data_test.go (hunk 2 above)
Comment (odeke-em) [reply go/proof_data_test.go:16]: We are doing fuzzing hence that change was needed and that isn't changing the interface as *testing.T implementing testing.TB so all existing code passes

File: go/ops.go (hunk 3 above)
Comment (odeke-em) [reply go/ops.go:97]: At least in the fuzzer and error tests that I ran, that condition was failing.

File: go/ops.go (hunk 4 above)
Comment (odeke-em) [reply go/ops.go:132]: The fuzzer flagged it.

File: go/ops.go (hunk 5 above)
Comment (odeke-em) [reply go/ops.go:140]: The fuzzer def flagged this condition too in mutations. In any case though, it is a defensive check, I highly recommend keeping that.

File: go/Makefile (hunk 8 above)
Comment (odeke-em) [reply go/Makefile]: Cool, I've reverted it, thanks for raising that.

File: go/fuzz_test.go (hunk 7 above)
Comment (odeke-em) [reply go/fuzz_test.go:203]: See the difference here though is that I want to mutate on the already calculated Spec & Root; otherwise it'll take so much much longer to generate the respective values which is also how the prior fuzzer wasn't able to quickly find such values. Sure I can move it up though.

File: go/fuzz_test.go (hunk 6 above)
Comment (odeke-em) [reply go/fuzz_test.go:133]: Done, I've moved it up. Thanks @crodriguezvega

File: .github/workflows/go.yml [hunk 10]
```diff
@@ -53,7 +53,7 @@ jobs:
           go-version: "1.21"
       - name: Run coverage
         working-directory: ./go
-        run: go test -race -coverprofile=coverage.txt -covermode=atomic
+        run: go test -short -race -coverprofile=coverage.txt -covermode=atomic
```
Comment (crodriguezvega) [inline .github/workflows/go.yml:56]: Should we remove `-short` here as well?

**Review by crodriguezvega — APPROVED** [review]
Thank you, @odeke-em. I still find weird that we need to explicitly check if the pointer receiver is `nil`. When I remove the check and run `make test` no tests fail... Maybe I am not running the tests correctly?

Besides, if that case was reachable, then why not add a similar check to all other functions with a pointer receiver?

File: .github/workflows/go.yml (hunk 10 above)
Comment (odeke-em) [reply .github/workflows/go.yml]: Thanks for flagging it, I've undone it.

File: go/ops.go (hunk 3 above)
Comment (odeke-em) [reply go/ops.go]: Done and reverted but I advise against it because there is a path in which op.CheckAgainstSpec is invoked directly without checking if the value was nil or not.

File: go/ops.go (hunk 4 above)
Comment (odeke-em) [reply go/ops.go]: Done, thanks!

**Comment by odeke-em** [comment]
>Besides, if that case was reachable, then why not add a similar check to all other functions with a pointer receiver?

I mean the fuzzer flagged it but sure I did undo it. Kindly help me take another look @crodriguezvega and then merge if possible. Thank you!

**Comment by odeke-em** [comment]
Just cc-ing the cosmos-sdk team to remind us to pull in the updated release once this code is merged in /cc @tac0turtle @julienrbrt @elias-orijtech

**Comment by tac0turtle** [comment]
@odeke-em sdk team doesnt maintain this repo. Carlos and the ibc team are best to do merges and approvals here

**Comment by odeke-em** [comment]
Oh okay, gotcha and thank you @tac0turtle!

**Review by AdityaSripal — APPROVED** [review]
Thank you @odeke-em !
